[package]
name = "ogeom-select"
description = "Spatial acceleration, picking and selection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
ogeom-core.workspace = true
ogeom-math.workspace = true
ogeom-geom.workspace = true
ogeom-topo.workspace = true
ogeom-mesh.workspace = true
ogeom-intersect.workspace = true

[dev-dependencies]
ogeom-algo.workspace = true
ogeom-bool.workspace = true
approx.workspace = true
proptest.workspace = true

[lints]
workspace = true
