[package]
name = "ogeom-heal"
description = "Shape healing: analysis, fixing and upgrading of imperfect geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ogeom-core.workspace = true
ogeom-math.workspace = true
ogeom-geom.workspace = true
ogeom-topo.workspace = true
ogeom-algo.workspace = true
ogeom-intersect.workspace = true

[dev-dependencies]
ogeom-io.workspace = true
ogeom-mesh.workspace = true
approx.workspace = true
proptest.workspace = true

[lints]
workspace = true
