#!/usr/bin/env python3
"""parity — the audit's ledger, its rendered form, and its gate.

Three committed files carry the parity audit, with three different authors:

- ``docs/parity/reference-index.tsv`` — generated by ``apisurf scope`` from a
  local reference checkout. One row per public header of the four in-scope
  modules, with its triage bucket. Regenerable, but committed so the audit
  survives the checkout being absent.
- ``docs/parity/parity.toml`` — hand-written. One block per *capability of
  ours*, claiming the reference headers it answers for. The only file a
  human edits.
- ``docs/PARITY.md`` — generated here, committed. The reviewable surface.

``generate`` renders PARITY.md from the first two. ``check`` is the gate
`tools/check.sh` runs: it validates the ledger against the index and against
the crate sources, and it never touches the reference tree — CI has no
checkout and needs none. ``exchange`` computes the live coverage figure for
the collapsed STEP/IGES entity rows, each format against its own sources.

The claim model
===============

A capability claims headers by explicit name or by glob (``BRepAlgoAPI_*``).
Claims must be disjoint and, together with the index's ``collapse`` rows and
per-rule drops, account for every header — a kept header claimed by nobody
fails the gate. That is the completeness check: our capabilities are the
primary key, the reference's headers are the checksum.

Verdicts, and what each must cite
=================================

- ``covered``    — symbols (checked against rustdoc output) and tests.
- ``partial``    — the same, plus ``restriction`` stating what is missing.
- ``absent``     — ``plan`` naming the PLAN.md/PARITY entry that owns it.
- ``divergent``  — ``reasoning``: we do this job on purpose another way.
- ``n/a``        — ``reasoning``: not a kernel capability for us, and why.
- ``unreviewed`` — nothing yet; counted against ``unreviewed_max``.
"""
from __future__ import annotations

import argparse
import collections
import fnmatch
import hashlib
import os
import re
import sys
import tomllib

INDEX = "docs/parity/reference-index.tsv"
LEDGER = "docs/parity/parity.toml"
RENDERED = "docs/PARITY.md"

VERDICTS = ("covered", "partial", "absent", "divergent", "n/a", "unreviewed")
EVIDENCE = {
    "covered": ("symbols", "tests"),
    "partial": ("symbols", "tests", "restriction"),
    "absent": ("plan",),
    "divergent": ("reasoning",),
    "n/a": ("reasoning",),
    "unreviewed": (),
}

# Why each drop rule is sound, rendered into PARITY.md so a reader with no
# reference checkout still sees what the drops were and can dispute them.
RULE_LEDGER = {
    "R1": "CDL generic instantiations — container words, The-/My- internals, "
          "chained Ofs. Rust generics express every one of these without a "
          "named type per instantiation; there is no capability to audit.",
    "R2": "The dedicated container packages (NCollection, TCol*, TCollection, "
          "TShort). Same ground as R1, package-shaped.",
    "R3": "Operating-system and infrastructure surface: memory, threads, "
          "signals, streams, strings, resources, persistence plumbing. The "
          "standard library's job. Cancellable progress is carved out and "
          "sits in the keep pool (V-PROGRESS).",
    "R4": "The TopOpeBRep* boolean family, superseded inside the reference "
          "by the BOPAlgo pipeline. Compatibility residue is not parity.",
    "R5": "OCAF persistence drivers inside DataExchange. The exchange "
          "document is in scope; the framework's serialization of it is not.",
}


def read_index(path: str) -> list[dict]:
    rows = []
    with open(path) as fh:
        header = fh.readline().rstrip("\n").split("\t")
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            row = dict(zip(header, parts))
            row["deprecated"] = int(row["deprecated"])
            row["usage"] = int(row["usage"])
            rows.append(row)
    return rows


def read_ledger(path: str) -> dict:
    with open(path, "rb") as fh:
        return tomllib.load(fh)


def index_checksum(path: str) -> str:
    return hashlib.sha256(open(path, "rb").read()).hexdigest()[:16]


# --------------------------------------------------------------------------
# claims
# --------------------------------------------------------------------------

def match_claims(caps: list[dict], kept: list[dict]) -> tuple[dict, dict]:
    """header -> capability id (unique), and capability id -> [headers]."""
    owner: dict[str, str] = {}
    claimed: dict[str, list[str]] = collections.defaultdict(list)
    errors = []
    stems = [r["header"] for r in kept]
    stem_set = set(stems)
    for cap in caps:
        for pat in cap.get("claims", []):
            if any(c in pat for c in "*?["):
                hits = fnmatch.filter(stems, pat)
            else:
                hits = [pat] if pat in stem_set else []
            if not hits:
                errors.append(f"{cap['id']}: claim '{pat}' matches nothing kept")
            for h in hits:
                if h in owner and owner[h] != cap["id"]:
                    errors.append(
                        f"header {h} claimed by both {owner[h]} and {cap['id']}")
                owner[h] = cap["id"]
                claimed[cap["id"]].append(h)
    if errors:
        raise SystemExit("claim errors:\n  " + "\n  ".join(errors))
    return owner, claimed


# --------------------------------------------------------------------------
# generate
# --------------------------------------------------------------------------

def cmd_generate(args) -> int:
    rows = read_index(args.index)
    ledger = read_ledger(args.ledger)
    caps = ledger.get("capability", [])
    kept = [r for r in rows if r["bucket"] == "keep"]
    owner, claimed = match_claims(caps, kept)

    by_verdict = collections.Counter(c["verdict"] for c in caps)
    n_claimed = len(owner)
    unclaimed = [r for r in kept if r["header"] not in owner]

    lines = []
    w = lines.append
    w("# Parity")
    w("")
    w("**Generated by `tools/parity.py generate` — do not edit.** The inputs")
    w(f"are `{args.index}` (generated from the reference tree by")
    w(f"`apisurf scope`) and `{args.ledger}` (hand-written; the only file a")
    w("person edits). `docs/SCOPE.md` defines the target; this file measures")
    w("against it.")
    w("")
    w("The primary key here is **our capabilities**. Each claims the reference")
    w("headers it answers for; the index is the completeness check. One")
    w("capability per thing a caller would ask for — not per class, and not")
    w("per package.")
    w("")
    w("## Where the audit stands")
    w("")
    w("| verdict | capabilities |")
    w("|---|---|")
    for v in VERDICTS:
        if by_verdict.get(v):
            w(f"| `{v}` | {by_verdict[v]} |")
    w("")
    kept_n = len(kept)
    w(f"{kept_n} reference headers in the reviewable pool; {n_claimed} claimed "
      f"by {len(caps)} capabilities, {len(unclaimed)} awaiting a claim. "
      f"Ratchet: `unreviewed_max = {ledger['audit']['unreviewed_max']}`.")
    w("")

    # capabilities, grouped by crate
    by_crate = collections.defaultdict(list)
    for c in caps:
        by_crate[c.get("crate", "?")].append(c)
    w("## Capabilities")
    for crate in sorted(by_crate):
        w("")
        w(f"### {crate}")
        w("")
        for c in sorted(by_crate[crate], key=lambda c: c["id"]):
            n = len(claimed.get(c["id"], []))
            w(f"- **{c['id']}** — {c['title']} · `{c['verdict']}` · "
              f"{n} header{'s' if n != 1 else ''} claimed")
            if c["verdict"] == "partial":
                w(f"  - *restriction:* {c['restriction']}")
            if c["verdict"] in ("divergent", "n/a"):
                w(f"  - *reasoning:* {c['reasoning']}")
            if c["verdict"] == "absent":
                w(f"  - *owned by:* {c['plan']}")

    # collapsed exchange rows
    w("")
    w("## Exchange entities (collapsed)")
    w("")
    w("One row per entity package; the coverage figures regenerate from the")
    w("entity tables in `ogeom-io` and are audited in tranche 3, not per")
    w("header.")
    w("")
    coll = collections.Counter()
    for r in rows:
        if r["bucket"] == "collapse":
            coll[(r["rule"], r["package"])] += 1
    w("| rule | package | headers |")
    w("|---|---|---|")
    for (rule, pkg), n in sorted(coll.items()):
        w(f"| {rule} | {pkg} | {n} |")

    # the N/A ledger for drops
    w("")
    w("## Dropped headers, and on whose authority")
    w("")
    w("Regenerate the full list with `apisurf scope`; sample it with")
    w("`--sample N`. A dispute with a rule is a change to `apisurf.py`, and")
    w("shows up as a diff naming exactly which headers moved.")
    w("")
    drops = collections.Counter(r["rule"] for r in rows if r["bucket"] == "drop")
    w("| rule | headers | justification |")
    w("|---|---|---|")
    for rule, n in sorted(drops.items()):
        w(f"| {rule} | {n} | {RULE_LEDGER[rule]} |")

    w("")
    w(f"<!-- index-checksum: {index_checksum(args.index)} -->")
    w("")

    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {args.out}: {len(caps)} capabilities, "
          f"{n_claimed}/{kept_n} kept headers claimed")
    return 0


# --------------------------------------------------------------------------
# exchange — the live coverage figure for the collapsed entity rows
# --------------------------------------------------------------------------

def camel_to_express(stem: str) -> str | None:
    """StepGeom_CartesianPoint -> CARTESIAN_POINT; RWStep* are readers/writers
    of the same entities and carry no entity of their own."""
    pkg, _, name = stem.partition("_")
    if not name or pkg.startswith("RW"):
        return None
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])", "_", name).upper()


def cmd_exchange(args) -> int:
    """Compare the collapsed entity rows against what ogeom-io implements.

    The measurement is textual on purpose: an EXPRESS name that appears in the
    reader or writer is an entity the code at least knows by name, and the
    figure is a ceiling, not a certificate — the per-entity fidelity question
    belongs to the exchange tests, not to a grep. Tranche 3 of the audit
    quotes this number with exactly that caveat.
    """
    rows = read_index(args.index)

    # Each format's coverage is measured against its own sources only. STEP
    # and IGES share entity names (GROUP, MANIFOLD_SOLID) and a shared grep
    # would report IGES coverage out of code that cannot read one byte of it.
    sources = {
        "C-STEP": ("crates/ogeom-io/src/step/read.rs",
                   "crates/ogeom-io/src/step/write.rs"),
        "C-IGES": tuple(sorted(
            os.path.join("crates/ogeom-io/src/iges", f)
            for f in (os.listdir("crates/ogeom-io/src/iges")
                      if os.path.isdir("crates/ogeom-io/src/iges") else [])
            if f.endswith(".rs"))),
    }

    for rule in ("C-STEP", "C-IGES"):
        impl = set()
        for path in sources[rule]:
            if os.path.exists(path):
                impl.update(re.findall(r'"([A-Z][A-Z_0-9]{3,})"', open(path).read()))
        entities = {}
        for r in rows:
            if r["bucket"] == "collapse" and r["rule"] == rule:
                e = camel_to_express(r["header"])
                if e:
                    entities.setdefault(e, 0)
                    entities[e] += r["usage"]
        have = {e for e in entities if e in impl}
        print(f"{rule}: {len(have)}/{len(entities)} entities named in ogeom-io")
        missing_used = sorted(((n, e) for e, n in entities.items()
                               if e not in impl and n > 0), reverse=True)
        if missing_used:
            print(f"  absent but used by the profiled consumer "
                  f"({len(missing_used)}):")
            for n, e in missing_used[:args.top]:
                print(f"    {n:>4}  {e}")
    return 0


# --------------------------------------------------------------------------
# check — the gate
# --------------------------------------------------------------------------

def workspace_crates() -> set[str]:
    """Doc-directory names of the crates currently in the workspace.

    `cargo doc` never removes output for crates that left, so `target/doc`
    accumulates ghosts — including everything moved to `outside/`. A citation
    resolving against a ghost would be exactly the quiet lie this gate exists
    to catch, so the walk is restricted to what `crates/` holds today.
    """
    out = set()
    for d in os.listdir("crates"):
        if os.path.isdir(os.path.join("crates", d)):
            out.add(d.replace("-", "_"))
    return out


def rustdoc_symbols(doc_root: str, crates: set[str]) -> set[str]:
    """Every documented item of the given crates, from rustdoc's file names.

    Rustdoc files an item under its *defining module* even when it is
    re-exported at the crate root — ogeom_algo::volume_properties lives at
    ogeom_algo/mass/fn.volume_properties.html — so the crate is the first
    path component and the module path in between is ignored. File names
    rather than HTML content: the set of items *is* the set of files.
    """
    syms = set()
    for crate in crates:
        root_dir = os.path.join(doc_root, crate)
        if not os.path.isdir(root_dir):
            continue
        for root, _dirs, files in os.walk(root_dir):
            for f in files:
                m = re.match(r"(?:struct|enum|trait|fn|constant|type|macro)\.(.+)\.html$", f)
                if m:
                    syms.add(f"{crate}::{m.group(1)}")
    return syms


def method_exists(doc_root: str, crate: str, type_name: str, method: str) -> bool:
    """A method cited as crate::Type::method must appear on the type's page."""
    import glob as _g
    for kind in ("struct", "enum", "trait"):
        for p in _g.glob(os.path.join(doc_root, crate, "**",
                                      f"{kind}.{type_name}.html"),
                         recursive=True):
            if re.search(rf'method\.{re.escape(method)}"',
                         open(p, errors="replace").read()):
                return True
    return False


def cmd_check(args) -> int:
    errors: list[str] = []
    rows = read_index(args.index)
    ledger = read_ledger(args.ledger)
    caps = ledger.get("capability", [])
    kept = [r for r in rows if r["bucket"] == "keep"]

    # schema and evidence
    seen_ids = set()
    for c in caps:
        cid = c.get("id", "<missing id>")
        if cid in seen_ids:
            errors.append(f"duplicate capability id {cid}")
        seen_ids.add(cid)
        for field in ("id", "title", "crate", "verdict"):
            if field not in c:
                errors.append(f"{cid}: missing field '{field}'")
        v = c.get("verdict")
        if v not in VERDICTS:
            errors.append(f"{cid}: unknown verdict '{v}'")
            continue
        for field in EVIDENCE[v]:
            if not c.get(field):
                errors.append(f"{cid}: verdict '{v}' requires '{field}'")

    # claims: total, disjoint, and matching something
    try:
        owner, _claimed = match_claims(caps, kept)
    except SystemExit as e:
        errors.append(str(e))
        owner = {}

    unclaimed = [r["header"] for r in kept if r["header"] not in owner]
    audit = ledger.get("audit", {})
    allow_unclaimed = audit.get("unclaimed_ok", False)
    if unclaimed and not allow_unclaimed:
        errors.append(f"{len(unclaimed)} kept headers claimed by nobody "
                      f"(first: {', '.join(unclaimed[:5])})")

    # ratchet
    n_unreviewed = sum(1 for c in caps if c.get("verdict") == "unreviewed")
    maxu = audit.get("unreviewed_max")
    if maxu is None:
        errors.append("audit.unreviewed_max missing")
    elif n_unreviewed > maxu:
        errors.append(f"{n_unreviewed} unreviewed capabilities exceeds "
                      f"unreviewed_max = {maxu}")

    # checksum: PARITY.md was generated from this index
    if os.path.exists(args.rendered):
        text = open(args.rendered).read()
        m = re.search(r"<!-- index-checksum: ([0-9a-f]+) -->", text)
        if not m:
            errors.append(f"{args.rendered} carries no index checksum")
        elif m.group(1) != index_checksum(args.index):
            errors.append(f"{args.rendered} is stale: regenerate with "
                          "`python3 tools/parity.py generate`")
    else:
        errors.append(f"{args.rendered} missing")

    # cited symbols resolve against rustdoc output, restricted to the crates
    # that are in the workspace today — target/doc accumulates ghosts of
    # crates that left, and resolving against one would be a quiet lie.
    doc = args.doc_root
    if os.path.isdir(doc):
        live = workspace_crates()
        syms = rustdoc_symbols(doc, live)
        for c in caps:
            for s in c.get("symbols", []):
                parts = s.split("::")
                if parts[0] not in live:
                    errors.append(f"{c['id']}: symbol {s} cites a crate that "
                                  "is not in the workspace")
                elif len(parts) == 2 and s not in syms:
                    errors.append(f"{c['id']}: symbol {s} not in {doc}")
                elif len(parts) == 3 and not method_exists(doc, *parts):
                    errors.append(f"{c['id']}: method {s} not in {doc}")
    else:
        errors.append(f"{doc} not built — run cargo doc first (check.sh does)")

    # cited tests resolve: file, or file::test_name
    for c in caps:
        for t in c.get("tests", []):
            path, _, name = t.partition("::")
            if not os.path.exists(path):
                errors.append(f"{c['id']}: test file {path} missing")
            elif name and name not in open(path, errors="replace").read():
                errors.append(f"{c['id']}: test {name} not in {path}")

    # Elsewhere lines agree: every package a lib.rs Elsewhere block names
    # must be claimed by some capability of that crate, once claims exist.
    if not allow_unclaimed:
        import glob as _g
        pkg_by_cap_crate = collections.defaultdict(set)
        hdr_pkg = {r["header"]: r["package"] for r in rows}
        for c in caps:
            for h in _claimed.get(c["id"], []):
                pkg_by_cap_crate[c["crate"]].add(hdr_pkg[h])
        kept_pkgs = {r["package"] for r in rows if r["bucket"] == "keep"}
        for lib in _g.glob("crates/*/src/lib.rs"):
            crate = lib.split(os.sep)[1]
            text = open(lib, errors="replace").read()
            m = re.search(r"\*Elsewhere:?\*(.*?)(?:\n//!\s*\n|\n[^/])", text, re.S)
            if not m:
                continue
            for pkg in re.findall(r"`([A-Za-z][A-Za-z0-9_]*)`", m.group(1)):
                # Only packages with kept rows create an obligation: naming a
                # dropped package (Standard, say) locates a concept, and there
                # is nothing there left to claim.
                if pkg in kept_pkgs and pkg not in pkg_by_cap_crate.get(crate, set()):
                    errors.append(f"{crate}: Elsewhere names {pkg} but no "
                                  f"capability of {crate} claims it")

    if errors:
        print("parity check FAILED:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        return 1
    print(f"parity check ok: {len(caps)} capabilities, "
          f"{n_unreviewed} unreviewed (max {maxu}), "
          f"{len(unclaimed)} unclaimed"
          + (" (allowed during skeleton phase)" if unclaimed else ""))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--index", default=INDEX)
    ap.add_argument("--ledger", default=LEDGER)
    ap.add_argument("--rendered", default=RENDERED)
    ap.add_argument("--doc-root", default="target/doc")
    sub = ap.add_subparsers(dest="command", required=True)
    sub.add_parser("generate", help="render docs/PARITY.md").set_defaults(func=cmd_generate)
    sub.add_parser("check", help="the gate check.sh runs").set_defaults(func=cmd_check)
    exch = sub.add_parser("exchange",
                          help="live entity coverage for the collapsed STEP/IGES rows")
    exch.add_argument("--top", type=int, default=15,
                      help="how many absent-but-used entities to list")
    exch.set_defaults(func=cmd_exchange)
    args = ap.parse_args()
    args.out = args.rendered
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
